services:
  - type: web
    name: tartanilla-admin
    env: python
    buildCommand: pip install -r requirements_production.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn tartanilla_admin.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true